mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - "8080:80"
  environment:
    - PMA_HOST=mysql
    - PMA_PORT=3306
    - PMA_USER=root
    - PMA_PASSWORD=root
  links:
    - mysql
